import sys
params = sys.argv[1].split("&")
output="<html><body><h1>Generated by python</h1><ul>"
for param in params:
	output += "<li>"+param.split("=")[0]+" with value:"+param.split("=")[1]+"</li>"
output = output + "</ul>\n</body>\n</html>"
print output
